// Week 03: MobileNetV2 NCNN inference demo
//
// This executable is intentionally narrow. It is a teaching-oriented baseline
// for understanding the NCNN inference loop before moving to YOLOv8n:
//
// - load the already-converted NCNN model
// - preprocess a fixed ImageNet image
// - run CPU inference
// - print top-k results with human-readable labels
// - benchmark steady-state inference latency
//
// The important part is not just "make it run", but make every stage visible
// so later debugging on Android can isolate problems quickly:
// image loading -> preprocessing -> tensor feeding -> inference -> postprocess
// -> benchmark.

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numeric>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#include "benchmark_core.h"
#if NCNN_VULKAN
#include "gpu.h"
#endif
#include "net.h"

namespace
{

using Clock = std::chrono::steady_clock;

struct Config
{
    // NCNN model artifacts generated by pnnx / NCNN converter.
    std::string param_path;
    std::string bin_path;

    // Evaluation inputs for this week-03 baseline.
    std::string image_path;
    std::string labels_path;
    enum class Backend
    {
        Cpu,
        Vulkan,
    } backend = Backend::Cpu;

    // Benchmark knobs. These are intentionally explicit so the same binary can
    // be used both for correctness checks and for latency sampling.
    int topk = 5;
    int warmup = 5;
    int runs = 20;
    int threads = 4;

    // MobileNetV2 expects 224x224 input. Keeping this as a config value makes
    // the code easier to reuse when the preprocessing shape changes later.
    int target_size = 224;
};

void print_usage(const char* argv0)
{
    // Keep the CLI self-documenting. This demo is intended to be run directly
    // from the terminal without any wrapper scripts.
    std::cerr << "Usage: " << argv0
              << " --param model.param --bin model.bin --image image.jpg --labels imagenet_classes.txt"
                 " [--backend cpu|vulkan] [--topk 5] [--warmup 5] [--runs 20] [--threads 4]\n";
}

bool parse_args(int argc, char** argv, Config& config)
{
    // Minimal hand-rolled parser is enough here. We want the binary to stay
    // dependency-light and easy to port into future CMake targets.
    for (int i = 1; i < argc; ++i)
    {
        const std::string arg = argv[i];
        auto require_value = [&](const char* name) -> const char*
        {
            if (i + 1 >= argc)
            {
                throw std::runtime_error(std::string("missing value for ") + name);
            }
            return argv[++i];
        };

        if (arg == "--param")
            config.param_path = require_value("--param");
        else if (arg == "--bin")
            config.bin_path = require_value("--bin");
        else if (arg == "--image")
            config.image_path = require_value("--image");
        else if (arg == "--labels")
            config.labels_path = require_value("--labels");
        else if (arg == "--backend")
        {
            const std::string value = require_value("--backend");
            if (value == "cpu")
                config.backend = Config::Backend::Cpu;
            else if (value == "vulkan")
                config.backend = Config::Backend::Vulkan;
            else
                throw std::runtime_error("unknown backend: " + value);
        }
        else if (arg == "--topk")
            config.topk = std::stoi(require_value("--topk"));
        else if (arg == "--warmup")
            config.warmup = std::stoi(require_value("--warmup"));
        else if (arg == "--runs")
            config.runs = std::stoi(require_value("--runs"));
        else if (arg == "--threads")
            config.threads = std::stoi(require_value("--threads"));
        else if (arg == "--target-size")
            config.target_size = std::stoi(require_value("--target-size"));
        else if (arg == "--help" || arg == "-h")
            return false;
        else
            throw std::runtime_error("unknown argument: " + arg);
    }

    if (config.param_path.empty() || config.bin_path.empty() || config.image_path.empty() || config.labels_path.empty())
    {
        throw std::runtime_error("missing required arguments");
    }

    return true;
}

std::vector<std::string> load_labels(const std::string& labels_path)
{
    // ImageNet labels are kept in a plain text file so the binary does not
    // need to embed any label table. This also matches the Python baseline.
    std::ifstream ifs(labels_path);
    if (!ifs)
    {
        throw std::runtime_error("failed to open labels file: " + labels_path);
    }

    std::vector<std::string> labels;
    std::string line;
    while (std::getline(ifs, line))
    {
        if (!line.empty())
            labels.push_back(line);
    }
    return labels;
}

struct LoadedImage
{
    int width = 0;
    int height = 0;
    std::vector<unsigned char> rgb;
};

LoadedImage load_image_rgb(const std::string& image_path)
{
    // stb_image is used here to keep the demo independent from OpenCV.
    // The result is normalized to 3-channel RGB so preprocessing is stable.
    int w = 0;
    int h = 0;
    int c = 0;
    //stbi_load 的作用是把输入的 JPEG/PNG 图片解码成一个连续存储的 RGB byte buffer。它返回一个指向这块内存的指针，以及图片的宽度、高度和通道数。
    unsigned char* pixels = stbi_load(image_path.c_str(), &w, &h, &c, 3);
    if (!pixels)
    {
        std::ostringstream oss;
        oss << "failed to load image: " << image_path << " (" << stbi_failure_reason() << ")";
        throw std::runtime_error(oss.str());
    }

    //LoadedImage 是我们定义的一个结构体，用来存储加载后的图像数据。它包含图像的宽度、高度和一个 RGB byte buffer。
    LoadedImage image;
    image.width = w;
    image.height = h;
    // stb_image 输出的像素是连续存储的 RGB byte buffer。我们把它复制到 std::vector<unsigned char> 里，方便后续处理和内存管理。
    image.rgb.assign(pixels, pixels + static_cast<std::size_t>(w) * static_cast<std::size_t>(h) * 3);
    stbi_image_free(pixels);
    return image;
}

ncnn::Mat preprocess_image(const LoadedImage& image, int target_size)
{
    // Match the ImageNet-style preprocessing used by the Python baseline:
    // 1. resize the short side to 256
    // 2. center-crop to 224x224
    // 3. normalize with ImageNet mean / std
    //
    // Keeping preprocessing aligned with the ONNX baseline is critical.
    // If top-1 confidence changes, we want to know whether the drift comes
    // from NCNN or from preprocessing.
    ncnn::Mat input = ncnn::Mat::from_pixels(image.rgb.data(), ncnn::Mat::PIXEL_RGB, image.width, image.height);

    // Resize the image while preserving aspect ratio. This mirrors the
    // torchvision Resize(256) behavior closely enough for this baseline.
    const int short_side = std::min(image.width, image.height);
    const float scale = 256.f / static_cast<float>(short_side);
    const int resized_w = std::max(target_size, static_cast<int>(std::lround(image.width * scale)));
    const int resized_h = std::max(target_size, static_cast<int>(std::lround(image.height * scale)));

    ncnn::Mat resized;
    ncnn::resize_bilinear(input, resized, resized_w, resized_h);

    // Center-crop keeps the object near the middle of the frame, which is the
    // standard ImageNet evaluation convention.
    const int crop_left = (resized_w - target_size) / 2;
    const int crop_right = resized_w - target_size - crop_left;
    const int crop_top = (resized_h - target_size) / 2;
    const int crop_bottom = resized_h - target_size - crop_top;

    ncnn::Mat cropped;
    ncnn::copy_cut_border(resized, cropped, crop_top, crop_bottom, crop_left, crop_right);

    // Normalize to the same distribution used by the pretrained torchvision
    // MobileNetV2 weights. If these constants change, classification scores
    // can shift significantly even if the model weights are unchanged.
    const float mean_vals[3] = {123.675f, 116.28f, 103.53f};
    const float norm_vals[3] = {1.f / 58.395f, 1.f / 57.12f, 1.f / 57.375f};
    cropped.substract_mean_normalize(mean_vals, norm_vals);
    return cropped;
}

} // namespace

int main(int argc, char** argv)
{
    Config config;
    try
    {
        if (!parse_args(argc, argv, config))
        {
            print_usage(argv[0]);
            return 0;
        }
    }
    catch (const std::exception& e)
    {
        print_usage(argv[0]);
        std::cerr << "argument error: " << e.what() << "\n";
        return 1;
    }

    try
    {
        // Net is the model container in NCNN. It owns the graph definition and
        // the weights. The extractor created from it is the per-inference
        // execution object.
        ncnn::Net net;

        // Choose the actual execution path explicitly. We do not pretend that
        // NCNN has a Metal backend; on Apple platforms the GPU path is Vulkan.
        switch (config.backend)
        {
        case Config::Backend::Cpu:
            net.opt.use_vulkan_compute = false;
            break;
        case Config::Backend::Vulkan:
#if NCNN_VULKAN
            if (ncnn::get_gpu_count() <= 0)
                throw std::runtime_error("requested Vulkan backend, but no Vulkan device is available");
            net.opt.use_vulkan_compute = true;
            net.set_vulkan_device(0);
#else
            throw std::runtime_error("requested Vulkan backend, but this NCNN build was compiled without Vulkan support");
#endif
            break;
        }
        net.opt.num_threads = config.threads;
        net.opt.lightmode = true;
        net.opt.use_packing_layout = true;

        // Measure model loading separately from inference. On device, session
        // creation and first inference can matter almost as much as steady-state
        // latency, so we keep the numbers distinct.
        const auto load_start = Clock::now();
        if (net.load_param(config.param_path.c_str()) != 0)
            throw std::runtime_error("failed to load param file: " + config.param_path);
        if (net.load_model(config.bin_path.c_str()) != 0)
            throw std::runtime_error("failed to load bin file: " + config.bin_path);
        const auto load_end = Clock::now();
        const double load_ms = std::chrono::duration<double, std::milli>(load_end - load_start).count();

        const std::vector<std::string> labels = load_labels(config.labels_path);
        const LoadedImage image = load_image_rgb(config.image_path);
        const ncnn::Mat input = preprocess_image(image, config.target_size);

        auto inference_once = [&]() -> std::vector<float> {
            ncnn::Extractor ex = net.create_extractor();
            ex.set_light_mode(true);
            ex.input("in0", input);

            ncnn::Mat output;
            if (ex.extract("out0", output) != 0)
                throw std::runtime_error("failed to extract output blob: out0");

            output = output.reshape(output.w * output.h * output.c);
            std::vector<float> logits(output.w);
            for (int i = 0; i < output.w; ++i)
                logits[i] = output[i];
            return week03::softmax(logits);
        };

        const std::vector<float> probabilities = inference_once();
        const std::vector<week03::TopKItem> ranked = week03::topk(probabilities, config.topk);

        std::cout << std::fixed << std::setprecision(3);
        std::cout << "[Config] param=" << config.param_path
                  << " bin=" << config.bin_path
                  << " image=" << config.image_path
                  << " labels=" << config.labels_path
                  << " backend=" << (config.backend == Config::Backend::Cpu ? "cpu" : "vulkan")
                  << " threads=" << config.threads
                  << " warmup=" << config.warmup
                  << " runs=" << config.runs
                  << " target_size=" << config.target_size << "\n";

        std::cout << "Requested backend: " << (config.backend == Config::Backend::Cpu ? "cpu" : "vulkan") << "\n";
        std::cout << "Backend: " << (config.backend == Config::Backend::Cpu ? "NCNN CPU" : "NCNN Vulkan") << "\n";

        std::cout << "[Input] width=" << image.width
                  << " height=" << image.height
                  << " resized=" << input.w << "x" << input.h
                  << " channels=" << input.c << "\n";

        std::cout << "[Load] model_load_ms=" << load_ms << "\n";

        if (!ranked.empty())
        {
            const week03::TopKItem& best = ranked.front();
            const std::string best_label =
                (best.class_id >= 0 && best.class_id < static_cast<int>(labels.size()))
                    ? labels[static_cast<size_t>(best.class_id)]
                    : "unknown";
            std::cout << "[Result] top1_idx=" << best.class_id
                      << " top1_label=" << best_label
                      << " top1_prob=" << (best.probability * 100.f) << "%\n";
        }

        std::cout << "[TopK]\n";
        for (int i = 0; i < static_cast<int>(ranked.size()); ++i)
        {
            const week03::TopKItem& item = ranked[i];
            const std::string label =
                (item.class_id >= 0 && item.class_id < static_cast<int>(labels.size()))
                    ? labels[static_cast<size_t>(item.class_id)]
                    : "unknown";
            std::cout << "#" << (i + 1)
                      << " idx=" << item.class_id
                      << " label=" << label
                      << " prob=" << (item.probability * 100.f) << "%\n";
        }

        // Benchmark the same input after warmup. This is the number we care
        // about when we later compare CPU vs Vulkan or Mac vs Android.
        const week03::BenchmarkResult result = week03::run_benchmark(inference_once, config.warmup, config.runs);
        std::cout << "[Benchmark] runs=" << result.times_ms.size()
                  << " mean_ms=" << result.mean
                  << " median_ms=" << result.median
                  << " p95_ms=" << result.p95
                  << "\n";

        return 0;
    }
    catch (const std::exception& e)
    {
        std::cerr << "error: " << e.what() << "\n";
        return 1;
    }
}
